services:
  - type: web
    name: toneprints
    runtime: static
    buildCommand: ""
    staticPublishPath: .
    pullRequestPreviewsEnabled: true
    routes:
      - type: rewrite
        source: /
        destination: /TonePrints.html
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
